---
metricPrefix: "Server|Component:8|Custom Metrics|WordCount2|"

filesToProcess:
  - name: file1.txt
    path: /Users/pradeep.nair/Documents/file1.txt
  - name: metrics.txt
    path: /Users/pradeep.nair/Documents/metrics.txt
  - name: README.txt
    path: /Users/pradeep.nair/Documents/README.txt
...